### ISSUE TITLE
Code needs documentation

### ISSUE THREAD

**Issue by luisortizuriarte** [JStiles9552/Assignment_3_CLIM_680#1]
As you write your code, keep in mind to document what you are doing. This will help other people (like me!) understand what you are doing and how to offer help, and it will help future you understand what you wrote!

Please add documentation to your code using markdown cells and inline comments so that a reader can understand your code.

**Comment by JStiles9552** [comment]
I have added a large amount of documentation to my revised Assignment 3 in markdown cells, hopefully my intentions are easier to understand now.

**Comment by luisortizuriarte** [comment]
The new markdown cell documentation makes your work much easier to follow. Thanks.

Closing this issue.
