### ISSUE TITLE
Tidying up after data exploration

### ISSUE THREAD

**Issue by luisortizuriarte** [JStiles9552/Assignment_3_CLIM_680#2]
In your submitted notebook, you dedicate a lot of cells to exploratory analysis with various outputs printed out. As you work and start resolving your issues, either remove erroneous code or consolidate it into single cells with fewer printouts. This will help you avoid duplication and errors and make it easier to document as well.

**Comment by JStiles9552** [comment]
I don't think I had many exploratory analysis cells in my initial Assignment 3, it was likely that I did not document my work in an adequate manner. Hopefully everything is more clear now that I have given documentation to the entire assignment.

**Comment by luisortizuriarte** [comment]
The documentation does help significantly with my original comment here. Closing this issue.
