### ISSUE TITLE
Plot labels

### ISSUE THREAD

**Issue by luisortizuriarte** [JStiles9552/Assignment_3_CLIM_680#4]
Several of your plots lack labels, which makes it very difficult to understand what we're looking at. Please label the figures and their axes as if you were submitting it to a publication.

**Comment by JStiles9552** [comment]
I have fixed the plots that did not have labels, looks like it was only the final plot that was missing the latitude and longitude labels

**Comment by luisortizuriarte** [comment]
Thanks!

It does seem like you still haven't added labels to the figures that are not maps (the timeseries near the beginning and the pink significance map towards the end). We will close this issue when those have labels.

**Comment by JStiles9552** [comment]
My mistake, I have added labels to both of the timeseries plots and the significance map (I'm not sure what the x and y-axis represent in this case or if they need labels at all, please let me know if its still wrong).

**Comment by luisortizuriarte** [comment]
All figures are now properly labeled. Closing this issue.
